name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       docker build . --tag ghcr.io/hhlim2/finalproject-docker-gcr-demo:latest
       docker push ghcr.io/hhlim2/finalproject-docker-gcr-demo:latest
